version: "3.7"

networks:
  default:
  traefik:
    external: true
    name: traefik

x-logging: &logging
  driver: gcplogs
  options:
    gcp-project: smoo-api
    gcp-meta-zone: us-east1
    gcp-meta-name: smoo-api
    mode: non-blocking

services:
  smoo-api:
    build: .
    user: "33:33"
    restart: unless-stopped
    logging: *logging
    volumes:
    - ./html/data/:/var/www/html/data/
    networks:
      default:
      traefik:
    labels:
    - traefik.frontend.rule=Host:api2.smoo.it,api.smoo.it
    - traefik.port=80
    environment:
      # public servers (from Discord)
      SMOO_SERVER_DC_PIP_1: piplup.smoo.it:1027
      SMOO_SERVER_DC_PIP_2: piplup.smoo.it:1028
      SMOO_SERVER_DC_PIP_3: piplus.smoo.it:1029
      SMOO_SERVER_DC_SAN_1: sanae.smoo.it:1027
      #SMOO_SERVER_DC_TMD_1: tmdog.smoo.it:1027
      SMOO_SERVER_DC_FOC_1: f0c0s.smoo.it:1027
      SMOO_SERVER_DC_SLE_1: sleepyy.smoo.it:1027
      SMOO_SERVER_DC_PAR_1: parknich.smoo.it:1027
      SMOO_SERVER_DC_ROC_1: rocket.smoo.it:1027
      SMOO_SERVER_DC_MUZ_1: larbe.org:1027
      SMOO_SERVER_DC_KAM_1: 66.220.29.106:1027

      # public servers (website only)
      SMOO_SERVER_WWW_KRO_1: krokilex.smoo.it:1027
      SMOO_SERVER_WWW_JEF_1: jeff.smoo.it:1027
      SMOO_SERVER_WWW_SNA_1: snafty.smoo.it:62102
      SMOO_SERVER_WWW_LUW_1: luwuna.smoo.it:1027
      SMOO_SERVER_WWW_LUW_2: luwuna.smoo.it:1028
      SMOO_SERVER_WWW_LUW_3: luwuna.smoo.it:1029

      # default refresh rate
      SMOO_EXPIRE: 10

      # refresh servers with JSON API more often
      SMOO_EXPIRE_JSON_PIP_1: piplup.smoo.it:1027:3
      SMOO_EXPIRE_JSON_PIP_2: piplup.smoo.it:1028:3
      SMOO_EXPIRE_JSON_PIP_3: piplus.smoo.it:1029:3
      SMOO_EXPIRE_JSON_RAD_1: radiated.smoo.it:1027:3
      SMOO_EXPIRE_JSON_LUW_1: luwuna.smoo.it:1027:3
      SMOO_EXPIRE_JSON_LUW_2: luwuna.smoo.it:1028:3
      SMOO_EXPIRE_JSON_LUW_3: luwuna.smoo.it:1029:3

      # refresh dead servers less often:
      SMOO_EXPIRE_DEAD_01: f0c0s.smoo.it:1027:30
      SMOO_EXPIRE_DEAD_02: yann.smoo.it:1027:30
      SMOO_EXPIRE_DEAD_03: jeff.smoo.it:1027:30
      SMOO_EXPIRE_DEAD_04: rocket.smoo.it:1027:30
      SMOO_EXPIRE_DEAD_05: sanae.smoo.it:1027:30
      SMOO_EXPIRE_DEAD_06: snafty.smoo.it:62102:30
