version: "3.7"

networks:
  default:
  traefik:
    external: true
    name: traefik

x-logging: &logging
  driver: gcplogs
  options:
    gcp-project: smoo-api
    gcp-meta-zone: us-east1
    gcp-meta-name: smoo-api
    mode: non-blocking

services:
  smoo-api:
    build: .
    user: "33:33"
    restart: unless-stopped
    logging: *logging
    volumes:
    - ./html/data/:/var/www/html/data/
    networks:
      default:
      traefik:
    labels:
    - traefik.frontend.rule=Host:api2.smoo.it,api.smoo.it
    - traefik.port=80
    environment:
      # public servers (from Discord)
      SMOO_SERVER_DC_PIP_1: piplup.smoo.it:1027
      SMOO_SERVER_DC_PIP_2: piplup.smoo.it:1028
      SMOO_SERVER_DC_KAM_1: kamron.smoo.it:1027
      SMOO_SERVER_DC_MUZ_1: muz.smoo.it:1027

      # public servers (website only)
      SMOO_SERVER_WWW_KRO_1: krokilex.smoo.it:1027
      SMOO_SERVER_WWW_COL_1: colbster.smoo.it:1027
      SMOO_SERVER_WWW_SCH_1: schwegelbin.smoo.it:1027
      SMOO_SERVER_WWW_HWG_1: hyperwg.smoo.it:1027
      SMOO_SERVER_WWW_HWG_2: hyperwg.smoo.it:1028
      SMOO_SERVER_WWW_HWG_3: hyperwg.smoo.it:1029
      SMOO_SERVER_WWW_SKY_1: skylanderfree.smoo.it:1027
      SMOO_SERVER_WWW_SKY_2: skylanderfree.smoo.it:1028
      SMOO_SERVER_WWW_2FA_1: 2fast.smoo.it:1027
      SMOO_SERVER_WWW_2FA_2: 2fast.smoo.it:1028
      SMOO_SERVER_WWW_2FA_3: 2fast.smoo.it:1029

      # default refresh rate
      SMOO_EXPIRE: 10

      # refresh servers with JSON API more often
      SMOO_EXPIRE_JSON_PIP_1: piplup.smoo.it:1027:3
      SMOO_EXPIRE_JSON_PIP_2: piplup.smoo.it:1028:3
      SMOO_EXPIRE_JSON_MUZ_1: muz.smoo.it:1027:3
      SMOO_EXPIRE_JSON_SCH_1: schwegelbin.smoo.it:1027:3
