version: "3.7"

services:
  smoo-api:
    build: .
    user: "33:33"
    restart: unless-stopped
    ports:
    - 8080:80
    volumes:
    - ./html/data/.env:/var/www/html/data/.env:ro
    environment:
      # public servers (from Discord)
      SMOO_SERVER_DC_PIP_01: piplup.smoo.it:1027
      SMOO_SERVER_DC_PIP_02: piplup.smoo.it:1028
      SMOO_SERVER_DC_KAM_01: kamron.smoo.it:1027
      SMOO_SERVER_DC_MUZ_01: muz.smoo.it:1027

      # public servers (website only)
      SMOO_SERVER_WWW_KRO_1: krokilex.smoo.it:1027
      SMOO_SERVER_WWW_COL_1: colbster.smoo.it:1027
      SMOO_SERVER_WWW_SCH_1: schwegelbin.smoo.it:1027
      SMOO_SERVER_WWW_HWG_1: hyperwg.smoo.it:1027
      SMOO_SERVER_WWW_HWG_2: hyperwg.smoo.it:1028
      SMOO_SERVER_WWW_HWG_3: hyperwg.smoo.it:1029
      SMOO_SERVER_WWW_SKY_1: skylanderfree.smoo.it:1027
      SMOO_SERVER_WWW_SKY_2: skylanderfree.smoo.it:1028
      SMOO_SERVER_WWW_2FA_1: 2fast.smoo.it:1027
      SMOO_SERVER_WWW_2FA_2: 2fast.smoo.it:1028

      # default refresh rate
      SMOO_EXPIRE: 10

      # refresh servers with JSON API more often
      SMOO_EXPIRE_JSON_PIP_1: piplup.smoo.it:1027:3
      SMOO_EXPIRE_JSON_PIP_2: piplup.smoo.it:1028:3
      SMOO_EXPIRE_JSON_MUZ_1: muz.smoo.it:1027:3
      SMOO_EXPIRE_JSON_SCH_1: schwegelbin.smoo.it:1027:3
